Repository West-Nottinghamshire-College/RectCompilerJava, pull requests merged in 2021-11, with the labels that each got.

#4 Added file reading
  Main.java
Labels: bug, enhancement

#5 Lexer fixes and started parsing flags
  Lexer.java
  Main.java
Labels: bug

#6 Removed badges
  README.md
Labels: documentation
